### PR TITLE
Fix Windows Hotkey

### PR DESCRIPTION
**Pull request by Kristinita**
See https://github.com/silentninja/easygit/blob/master/Default%20(Windows).sublime-keymap.

### CODE REVIEW

**Comment by silentninja** [comment]
Thanks for the PR.

**Comment by Kristinita** [comment]
@silentninja , you don't have issue tracker in your fork repository, so I'm writing here.

I copied myself your fork plugin Easygit, I run the command. 

```
key evt: shift+super+g
command: add_then_commit_then_push {"targeted": "all"}
```

But I appear with the following message dialog box.

`error: Problem commiting files, do it manually!`

Windows 10 Education
Sublime Text 3 Build 3114

Please, fix. 

Thanks.

**Comment by silentninja** [comment]
I have enabled issue tracker.Please do open an issue.

As for the problem you are facing, can you try committing it manually and see if git throws up any error or asks for additional information. Right now it works only if commit works in one go and throws up error if any intermediate step like merge has to be performed.

**Comment by Kristinita** [comment]
@silentninja ,  I input `git add .` , `git commit -m "Example"` , `git push` to the Git Bash and  [Git](https://packagecontrol.io/packages/Git) plugin for Sublime Text. In both cases, there is normally push. Only Easygit I have a problem. On [Ivanca Easygit](https://github.com/Ivanca/easygit) I don't have this problem.

This problem not reproduce on a Windows for you?

Thanks.

**Pull request merged**
